<?php

namespace AppBundle\Repository;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findFiltered(array $filter){
        $qb= $this->createQueryBuilder('cntr');

        $qb->addOrderBy('cntr.onDate','DESC');
        $qb->where(' (:dateBegin IS NULL AND :dateEnd IS NULL) '."\r\n".
            'OR (:dateBegin IS NULL AND :dateEnd >= cntr.onDate) '."\r\n".
            'OR (:dateBegin <= cntr.onDate AND :dateEnd IS NULL) '."\r\n".
            'OR (cntr.onDate BETWEEN :dateBegin AND :dateEnd ) ');
        $qb->setParameters(['dateBegin'=>$filter['dateB'], 'dateEnd'=>$filter['dateE']]);
        if ( !is_null($filter['place']) ) $qb->andWhere($qb->expr()->eq('cntr.place',':place'))->setParameter ('place', $filter['place']->getId());
        if ( !is_null($filter['service']) ) $qb->andWhere($qb->expr()->eq('cntr.service',':service'))->setParameter ('service', $filter['service']->getId());
        
        return $qb->getQuery()->getResult();
    }
    
    
    
}
