<?php

namespace AppBundle\Repository;

use AppBundle\Classes\Doctrine\RepositoryTrait;

/**
 * PaymentInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentInfoRepository extends \Doctrine\ORM\EntityRepository {
    
    use RepositoryTrait;
    
    public function hasChildren($id) {
        $tables = [ 'place_service'=>'payment_info'];
        return $this->_hasChildren($id, $tables);
    }
    
}
