<?php

namespace AppBundle\Repository;

/**
 * PlaceServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
