<?php

namespace AppBundle\Repository;

use AppBundle\Entity;
use AppBundle\Classes\Doctrine\RepositoryTrait;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
    
    public function hasChildren($id) {
        $tables = [
            'tariff'=>'place_id',
            'place_service'=>'place_id',
            'counter'=>'place_id',
            'scale'=>'place_id',
            'payment_info'=>'place_id'
        ];
        return $this->_hasChildren($id, $tables);
    }
    
}
