<?php

namespace AppBundle\Repository;

/**
 * ServiceParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
