<?php

namespace AppBundle\Repository;

use AppBundle\Entity;

/**
 * TariffValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffValueRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    
    
}
