<?php

namespace AppBundle\Repository;

/**
 * UserPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
