<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Query\Parameter;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository  implements  UserLoaderInterface
{
    
    /**
     * 
     * @param string $username
     * @return \AppBundle\Entity\User|null
     */
    public function loadUserByUsername($username) {
        return $this->findOneBy(['email'=>$username, 'emailIsConfirmed'=>true]);
    }

    /**
     * 
     * @param string $email
     * @param string $oneTimePass
     * @return \AppBundle\Entity\User|null 
     */
    public function loadUserForEmailConfirmation($email, $oneTimePass) {
        $qb = $this->createQueryBuilder('u');
        $qb ->where("u.email = :email \r\n AND u.oneTimePass = :oneTimePass \r\n AND u.otpDateExp >= :otpDateExp \r\n" )
            ->andWhere($qb->expr()->isNotNull('u.otpDateExp'))
            ->setParameters(new ArrayCollection([
                new Parameter('email',$email),
                new Parameter('oneTimePass',$oneTimePass),
                new Parameter('otpDateExp',new \DateTime())
            ]));
        return  $qb->getQuery()->getOneOrNullResult();
    }
    
    
}
